package com.example.hua.normalusedemo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.hua.normalusedemo.bean.GoodsInfo;

import com.example.hua.normalusedemo.dao.GoodsInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig goodsInfoDaoConfig;

    private final GoodsInfoDao goodsInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        goodsInfoDaoConfig = daoConfigMap.get(GoodsInfoDao.class).clone();
        goodsInfoDaoConfig.initIdentityScope(type);

        goodsInfoDao = new GoodsInfoDao(goodsInfoDaoConfig, this);

        registerDao(GoodsInfo.class, goodsInfoDao);
    }
    
    public void clear() {
        goodsInfoDaoConfig.clearIdentityScope();
    }

    public GoodsInfoDao getGoodsInfoDao() {
        return goodsInfoDao;
    }

}
